version: '3'

services:

  springboot:
    build: .
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod


  nginx:
    build: ./nginx
    container_name: nginx-proxy
    depends_on:
      - springboot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl


  #  unnecessary for development on local environment
  #  coturn:
  #    image: instrumentisto/coturn
  #    restart: always
  #    environment:
  #      - TURN_PUBLIC_IP=<IP_ADDRESS>
  #      - TURN_REALM=username
  #      - TURN_SECRET=password
  #    ports:
  #      - "3478:3478/udp"
  #      - "3478:3478/tcp"
  #      - "65435-65535:65435-65535/udp"